### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to pvpstats v1.5.3

### ISSUE THREAD

**Issue by CM8DoubleCheck** [slipcor/PVPStats#27]
Hi, I'm receiving this error below on Paper build 387 for 1.15.2:

```
28.08 00:42:23 [Server] ERROR Could not pass event EntityDamageByEntityEvent to pvpstats v1.5.3
28.08 00:42:23 [Server] INFO java.lang.NullPointerException: null
28.08 00:42:23 [Server] INFO at net.slipcor.pvpstats.classes.PlayerDamageHistory.commitPlayerDamage(PlayerDamageHistory.java:12) ~[?:?]
28.08 00:42:23 [Server] INFO at net.slipcor.pvpstats.listeners.PlayerListener.onPlayerDamage(PlayerListener.java:72) ~[?:?]
28.08 00:42:23 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
28.08 00:42:23 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:874) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:780) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.Explosion.a(Explosion.java:188) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1025) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.createExplosion(WorldServer.java:1648) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1015) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityEnderCrystal.damageEntity(EntityEnderCrystal.java:104) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1753) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2105) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-387]
28.08 00:42:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by slipcor** [comment]
Here is a hotfix for you :)

http://pa.slipcor.net/pvpstats.jar

I will release this after I finished breakfast :D

**Comment by CM8DoubleCheck** [comment]
Awesome, I just tested it and all is good now :)
